import type {
  Activity,
  AppNotification,
  Client,
  Lead,
  Task,
} from "@/lib/types"

export const owners = [
  "Alex Morgan",
  "Emma Davis",
  "John Smith",
  "Priya Nair",
] as const

export const leadSources = [
  "Website",
  "Referral",
  "LinkedIn",
  "Cold Outreach",
  "Event",
  "Inbound Call",
] as const

export const industries = [
  "Technology",
  "E-commerce",
  "Finance",
  "Healthcare",
  "Marketing",
  "Manufacturing",
  "Education",
] as const

export const leads: Lead[] = [
  {
    id: "l1",
    name: "Sarah Johnson",
    company: "Acme Digital",
    email: "sarah@acmedigital.com",
    phone: "+1 (415) 555-0182",
    source: "Referral",
    status: "Qualified",
    dealValue: 12500,
    owner: "Alex Morgan",
    lastContact: "Today",
    priority: "High",
    notes: "Interested in a full website redesign and ongoing retainer.",
  },
  {
    id: "l2",
    name: "Michael Chen",
    company: "Vertex Solutions",
    email: "m.chen@vertexsol.com",
    phone: "+1 (212) 555-0143",
    source: "LinkedIn",
    status: "Proposal",
    dealValue: 24000,
    owner: "Emma Davis",
    lastContact: "Yesterday",
    priority: "High",
    notes: "Proposal sent for Q3 marketing engagement.",
  },
  {
    id: "l3",
    name: "Emily Davis",
    company: "BluePeak Consulting",
    email: "emily@bluepeak.io",
    phone: "+1 (303) 555-0199",
    source: "Website",
    status: "Contacted",
    dealValue: 8500,
    owner: "Alex Morgan",
    lastContact: "2 days ago",
    priority: "Medium",
    notes: "Requested a discovery call next week.",
  },
  {
    id: "l4",
    name: "Daniel Wilson",
    company: "NovaTech Systems",
    email: "daniel@novatech.dev",
    phone: "+1 (650) 555-0176",
    source: "Event",
    status: "Negotiation",
    dealValue: 31000,
    owner: "John Smith",
    lastContact: "3 days ago",
    priority: "High",
    notes: "Negotiating contract terms and start date.",
  },
  {
    id: "l5",
    name: "Olivia Martinez",
    company: "BrightWorks Agency",
    email: "olivia@brightworks.co",
    phone: "+1 (312) 555-0128",
    source: "Cold Outreach",
    status: "New",
    dealValue: 6800,
    owner: "Priya Nair",
    lastContact: "4 days ago",
    priority: "Low",
  },
  {
    id: "l6",
    name: "James Anderson",
    company: "CloudCore",
    email: "james@cloudcore.app",
    phone: "+1 (206) 555-0111",
    source: "Inbound Call",
    status: "Qualified",
    dealValue: 18500,
    owner: "Emma Davis",
    lastContact: "Today",
    priority: "Medium",
  },
  {
    id: "l7",
    name: "Sophia Lee",
    company: "Apex Innovations",
    email: "sophia@apexinnov.com",
    phone: "+1 (408) 555-0164",
    source: "Referral",
    status: "New",
    dealValue: 9500,
    owner: "Alex Morgan",
    lastContact: "5 days ago",
    priority: "Medium",
  },
  {
    id: "l8",
    name: "William Brown",
    company: "PixelWorks",
    email: "will@pixelworks.design",
    phone: "+1 (503) 555-0155",
    source: "Website",
    status: "Contacted",
    dealValue: 7200,
    owner: "John Smith",
    lastContact: "6 days ago",
    priority: "Low",
  },
  {
    id: "l9",
    name: "Ava Thompson",
    company: "GrowthLabs",
    email: "ava@growthlabs.io",
    phone: "+1 (617) 555-0137",
    source: "LinkedIn",
    status: "Proposal",
    dealValue: 21500,
    owner: "Priya Nair",
    lastContact: "Yesterday",
    priority: "High",
  },
  {
    id: "l10",
    name: "Ethan Garcia",
    company: "TechVista",
    email: "ethan@techvista.com",
    phone: "+1 (720) 555-0148",
    source: "Event",
    status: "Won",
    dealValue: 27500,
    owner: "Alex Morgan",
    lastContact: "1 week ago",
    priority: "Medium",
  },
  {
    id: "l11",
    name: "Isabella Rodriguez",
    company: "Acme Digital",
    email: "bella@acmedigital.com",
    phone: "+1 (415) 555-0190",
    source: "Referral",
    status: "Negotiation",
    dealValue: 15800,
    owner: "Emma Davis",
    lastContact: "2 days ago",
    priority: "High",
  },
  {
    id: "l12",
    name: "Noah Walker",
    company: "Vertex Solutions",
    email: "noah@vertexsol.com",
    phone: "+1 (212) 555-0122",
    source: "Cold Outreach",
    status: "New",
    dealValue: 5400,
    owner: "John Smith",
    lastContact: "1 week ago",
    priority: "Low",
  },
  {
    id: "l13",
    name: "Mia Hall",
    company: "CloudCore",
    email: "mia@cloudcore.app",
    phone: "+1 (206) 555-0170",
    source: "Website",
    status: "Qualified",
    dealValue: 13200,
    owner: "Priya Nair",
    lastContact: "3 days ago",
    priority: "Medium",
  },
  {
    id: "l14",
    name: "Benjamin Young",
    company: "GrowthLabs",
    email: "ben@growthlabs.io",
    phone: "+1 (617) 555-0159",
    source: "LinkedIn",
    status: "Contacted",
    dealValue: 10400,
    owner: "Alex Morgan",
    lastContact: "4 days ago",
    priority: "Medium",
  },
  {
    id: "l15",
    name: "Charlotte King",
    company: "PixelWorks",
    email: "charlotte@pixelworks.design",
    phone: "+1 (503) 555-0133",
    source: "Referral",
    status: "Lost",
    dealValue: 8900,
    owner: "Emma Davis",
    lastContact: "2 weeks ago",
    priority: "Low",
  },
]

export const clients: Client[] = [
  {
    id: "c1",
    name: "Sarah Johnson",
    company: "Acme Digital",
    email: "sarah@acmedigital.com",
    phone: "+1 (415) 555-0182",
    industry: "Marketing",
    engagement: "Active",
    projectStatus: "On Track",
    owner: "Alex Morgan",
    contractValue: 48000,
    lastActivity: "Today",
    startDate: "Jan 15, 2026",
    contractEnd: "Jan 14, 2027",
    summary:
      "Acme Digital is currently working with the agency on a website redesign and digital marketing engagement.",
    projects: [
      { name: "Website Redesign", status: "On Track" },
      { name: "Digital Marketing Campaign", status: "On Track" },
      { name: "SEO Optimization", status: "At Risk" },
    ],
    notes: [
      {
        id: "n1",
        author: "Alex Morgan",
        text: "Kickoff meeting went well. Client is aligned on the redesign timeline.",
        createdAt: "Sep 18, 2026",
      },
      {
        id: "n2",
        author: "Emma Davis",
        text: "Shared the first round of homepage concepts. Awaiting feedback.",
        createdAt: "Sep 20, 2026",
      },
    ],
  },
  {
    id: "c2",
    name: "Michael Chen",
    company: "Vertex Solutions",
    email: "m.chen@vertexsol.com",
    phone: "+1 (212) 555-0143",
    industry: "Technology",
    engagement: "Onboarding",
    projectStatus: "On Track",
    owner: "Emma Davis",
    contractValue: 62000,
    lastActivity: "Yesterday",
    startDate: "Sep 1, 2026",
    contractEnd: "Aug 31, 2027",
    summary:
      "Vertex Solutions recently signed on for a brand refresh and go-to-market strategy.",
    projects: [
      { name: "Brand Refresh", status: "On Track" },
      { name: "Go-to-Market Strategy", status: "On Track" },
    ],
    notes: [
      {
        id: "n1",
        author: "Emma Davis",
        text: "Onboarding docs sent. Setting up shared workspace this week.",
        createdAt: "Sep 5, 2026",
      },
    ],
  },
  {
    id: "c3",
    name: "Daniel Wilson",
    company: "NovaTech Systems",
    email: "daniel@novatech.dev",
    phone: "+1 (650) 555-0176",
    industry: "Technology",
    engagement: "Active",
    projectStatus: "At Risk",
    owner: "John Smith",
    contractValue: 85000,
    lastActivity: "3 days ago",
    startDate: "Mar 10, 2026",
    contractEnd: "Mar 9, 2027",
    summary:
      "NovaTech Systems is scaling their product marketing with a multi-channel campaign.",
    projects: [
      { name: "Product Launch Campaign", status: "At Risk" },
      { name: "Content Strategy", status: "On Track" },
    ],
    notes: [
      {
        id: "n1",
        author: "John Smith",
        text: "Campaign timeline slipping. Need to re-align on deliverables.",
        createdAt: "Sep 17, 2026",
      },
    ],
  },
  {
    id: "c4",
    name: "James Anderson",
    company: "CloudCore",
    email: "james@cloudcore.app",
    phone: "+1 (206) 555-0111",
    industry: "Technology",
    engagement: "Active",
    projectStatus: "On Track",
    owner: "Priya Nair",
    contractValue: 54000,
    lastActivity: "Today",
    startDate: "Feb 20, 2026",
    contractEnd: "Feb 19, 2027",
    summary:
      "CloudCore engaged the agency for demand generation and paid media management.",
    projects: [
      { name: "Paid Media Management", status: "On Track" },
      { name: "Demand Generation", status: "On Track" },
    ],
    notes: [],
  },
  {
    id: "c5",
    name: "Ava Thompson",
    company: "GrowthLabs",
    email: "ava@growthlabs.io",
    phone: "+1 (617) 555-0137",
    industry: "E-commerce",
    engagement: "At Risk",
    projectStatus: "Delayed",
    owner: "Emma Davis",
    contractValue: 39000,
    lastActivity: "1 week ago",
    startDate: "Apr 5, 2026",
    contractEnd: "Oct 4, 2026",
    summary:
      "GrowthLabs is a performance marketing client with an upcoming renewal decision.",
    projects: [
      { name: "Conversion Optimization", status: "Delayed" },
      { name: "Email Automation", status: "On Track" },
    ],
    notes: [
      {
        id: "n1",
        author: "Emma Davis",
        text: "Client raised concerns about ROI. Scheduling a review call.",
        createdAt: "Sep 14, 2026",
      },
    ],
  },
  {
    id: "c6",
    name: "Ethan Garcia",
    company: "TechVista",
    email: "ethan@techvista.com",
    phone: "+1 (720) 555-0148",
    industry: "Finance",
    engagement: "Active",
    projectStatus: "On Track",
    owner: "Alex Morgan",
    contractValue: 72000,
    lastActivity: "2 days ago",
    startDate: "May 1, 2026",
    contractEnd: "Apr 30, 2027",
    summary:
      "TechVista partners with the agency on thought leadership and content marketing.",
    projects: [
      { name: "Thought Leadership", status: "On Track" },
      { name: "Content Marketing", status: "On Track" },
    ],
    notes: [],
  },
  {
    id: "c7",
    name: "Olivia Martinez",
    company: "BrightWorks Agency",
    email: "olivia@brightworks.co",
    phone: "+1 (312) 555-0128",
    industry: "Marketing",
    engagement: "Onboarding",
    projectStatus: "On Track",
    owner: "Priya Nair",
    contractValue: 28000,
    lastActivity: "4 days ago",
    startDate: "Sep 10, 2026",
    contractEnd: "Sep 9, 2027",
    summary:
      "BrightWorks Agency is onboarding for a co-marketing and referral partnership.",
    projects: [{ name: "Co-Marketing Program", status: "On Track" }],
    notes: [],
  },
  {
    id: "c8",
    name: "Sophia Lee",
    company: "Apex Innovations",
    email: "sophia@apexinnov.com",
    phone: "+1 (408) 555-0164",
    industry: "Manufacturing",
    engagement: "Completed",
    projectStatus: "Completed",
    owner: "John Smith",
    contractValue: 45000,
    lastActivity: "3 weeks ago",
    startDate: "Nov 1, 2025",
    contractEnd: "Aug 31, 2026",
    summary:
      "Apex Innovations completed a successful rebranding and web development project.",
    projects: [
      { name: "Rebranding", status: "Completed" },
      { name: "Web Development", status: "Completed" },
    ],
    notes: [
      {
        id: "n1",
        author: "John Smith",
        text: "Project wrapped up. Exploring a renewal for ongoing support.",
        createdAt: "Aug 28, 2026",
      },
    ],
  },
  {
    id: "c9",
    name: "William Brown",
    company: "PixelWorks",
    email: "will@pixelworks.design",
    phone: "+1 (503) 555-0155",
    industry: "Technology",
    engagement: "Active",
    projectStatus: "On Track",
    owner: "Alex Morgan",
    contractValue: 33000,
    lastActivity: "Yesterday",
    startDate: "Jun 15, 2026",
    contractEnd: "Jun 14, 2027",
    summary:
      "PixelWorks works with the agency on UX research and product design support.",
    projects: [
      { name: "UX Research", status: "On Track" },
      { name: "Design System", status: "On Track" },
    ],
    notes: [],
  },
  {
    id: "c10",
    name: "Isabella Rodriguez",
    company: "BluePeak Consulting",
    email: "bella@bluepeak.io",
    phone: "+1 (303) 555-0199",
    industry: "Finance",
    engagement: "Active",
    projectStatus: "On Track",
    owner: "Emma Davis",
    contractValue: 58000,
    lastActivity: "5 days ago",
    startDate: "Jul 1, 2026",
    contractEnd: "Jun 30, 2027",
    summary:
      "BluePeak Consulting engaged the agency for lead generation and CRM strategy.",
    projects: [
      { name: "Lead Generation", status: "On Track" },
      { name: "CRM Strategy", status: "On Track" },
    ],
    notes: [],
  },
]

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Follow up on proposal",
    description: "Check in with Acme Digital on the redesign proposal.",
    related: "Acme Digital",
    relatedType: "Client",
    dueDate: "2026-09-21",
    dueLabel: "Today",
    priority: "High",
    assignedTo: "Alex Morgan",
    status: "To Do",
  },
  {
    id: "t2",
    title: "Schedule discovery call",
    description: "Set up an intro call to scope the engagement.",
    related: "Vertex Solutions",
    relatedType: "Lead",
    dueDate: "2026-09-22",
    dueLabel: "Tomorrow",
    priority: "Medium",
    assignedTo: "Emma Davis",
    status: "To Do",
  },
  {
    id: "t3",
    title: "Contract review",
    description: "Review updated contract terms before signing.",
    related: "NovaTech Systems",
    relatedType: "Client",
    dueDate: "2026-09-24",
    dueLabel: "Sep 24",
    priority: "High",
    assignedTo: "John Smith",
    status: "In Progress",
  },
  {
    id: "t4",
    title: "Send onboarding docs",
    description: "Share the onboarding packet and kickoff agenda.",
    related: "BrightWorks Agency",
    relatedType: "Client",
    dueDate: "2026-09-23",
    dueLabel: "Sep 23",
    priority: "Medium",
    assignedTo: "Priya Nair",
    status: "To Do",
  },
  {
    id: "t5",
    title: "Prepare campaign report",
    description: "Compile September performance metrics.",
    related: "CloudCore",
    relatedType: "Client",
    dueDate: "2026-09-21",
    dueLabel: "Today",
    priority: "High",
    assignedTo: "Priya Nair",
    status: "In Progress",
  },
  {
    id: "t6",
    title: "Quarterly business review",
    description: "Host QBR with the TechVista leadership team.",
    related: "TechVista",
    relatedType: "Client",
    dueDate: "2026-09-25",
    dueLabel: "Sep 25",
    priority: "Medium",
    assignedTo: "Alex Morgan",
    status: "To Do",
  },
  {
    id: "t7",
    title: "Retention check-in call",
    description: "Address ROI concerns and renewal options.",
    related: "GrowthLabs",
    relatedType: "Client",
    dueDate: "2026-09-19",
    dueLabel: "Sep 19",
    priority: "High",
    assignedTo: "Emma Davis",
    status: "Overdue",
  },
  {
    id: "t8",
    title: "Send follow-up email",
    description: "Recap the discovery call and next steps.",
    related: "BluePeak Consulting",
    relatedType: "Lead",
    dueDate: "2026-09-22",
    dueLabel: "Tomorrow",
    priority: "Low",
    assignedTo: "Alex Morgan",
    status: "To Do",
  },
  {
    id: "t9",
    title: "Design concept revisions",
    description: "Incorporate client feedback on homepage concepts.",
    related: "Acme Digital",
    relatedType: "Client",
    dueDate: "2026-09-26",
    dueLabel: "Sep 26",
    priority: "Medium",
    assignedTo: "Emma Davis",
    status: "To Do",
  },
  {
    id: "t10",
    title: "Update CRM records",
    description: "Log recent activity and update deal stages.",
    related: "PixelWorks",
    relatedType: "Client",
    dueDate: "2026-09-18",
    dueLabel: "Sep 18",
    priority: "Low",
    assignedTo: "John Smith",
    status: "Completed",
  },
  {
    id: "t11",
    title: "Prepare proposal draft",
    description: "Draft the marketing retainer proposal.",
    related: "GrowthLabs",
    relatedType: "Lead",
    dueDate: "2026-09-27",
    dueLabel: "Sep 27",
    priority: "High",
    assignedTo: "Priya Nair",
    status: "To Do",
  },
  {
    id: "t12",
    title: "Confirm meeting agenda",
    description: "Finalize the agenda for the negotiation call.",
    related: "NovaTech Systems",
    relatedType: "Lead",
    dueDate: "2026-09-20",
    dueLabel: "Sep 20",
    priority: "Medium",
    assignedTo: "John Smith",
    status: "Overdue",
  },
  {
    id: "t13",
    title: "Share case study",
    description: "Send a relevant case study to build confidence.",
    related: "CloudCore",
    relatedType: "Lead",
    dueDate: "2026-09-15",
    dueLabel: "Sep 15",
    priority: "Low",
    assignedTo: "Emma Davis",
    status: "Completed",
  },
  {
    id: "t14",
    title: "Renewal proposal",
    description: "Prepare a renewal proposal for the completed project.",
    related: "Apex Innovations",
    relatedType: "Client",
    dueDate: "2026-09-28",
    dueLabel: "Sep 28",
    priority: "Medium",
    assignedTo: "John Smith",
    status: "To Do",
  },
  {
    id: "t15",
    title: "Monthly invoice",
    description: "Send the September invoice and payment reminder.",
    related: "TechVista",
    relatedType: "Client",
    dueDate: "2026-09-17",
    dueLabel: "Sep 17",
    priority: "Low",
    assignedTo: "Alex Morgan",
    status: "Overdue",
  },
]

export const activities: Activity[] = [
  {
    id: "a1",
    type: "Leads",
    actor: "Alex Morgan",
    action: "moved to Qualified",
    entity: "Sarah Johnson",
    time: "2026-09-21T09:50:00",
    timeLabel: "10 minutes ago",
  },
  {
    id: "a2",
    type: "Leads",
    actor: "Emma Davis",
    action: "added a new lead",
    entity: "Vertex Solutions",
    time: "2026-09-21T09:00:00",
    timeLabel: "1 hour ago",
  },
  {
    id: "a3",
    type: "Communication",
    actor: "Alex Morgan",
    action: "sent a proposal to",
    entity: "Acme Digital",
    time: "2026-09-21T07:00:00",
    timeLabel: "3 hours ago",
  },
  {
    id: "a4",
    type: "Tasks",
    actor: "John Smith",
    action: "completed a task for",
    entity: "NovaTech Systems",
    time: "2026-09-20T16:30:00",
    timeLabel: "Yesterday",
  },
  {
    id: "a5",
    type: "Clients",
    actor: "Priya Nair",
    action: "updated the contract for",
    entity: "CloudCore",
    time: "2026-09-20T14:10:00",
    timeLabel: "Yesterday",
  },
  {
    id: "a6",
    type: "Communication",
    actor: "Emma Davis",
    action: "scheduled a meeting with",
    entity: "GrowthLabs",
    time: "2026-09-20T11:20:00",
    timeLabel: "Yesterday",
  },
  {
    id: "a7",
    type: "Leads",
    actor: "Priya Nair",
    action: "moved to Proposal",
    entity: "Ava Thompson",
    time: "2026-09-19T15:45:00",
    timeLabel: "2 days ago",
  },
  {
    id: "a8",
    type: "Clients",
    actor: "Alex Morgan",
    action: "added a note for",
    entity: "TechVista",
    time: "2026-09-19T13:00:00",
    timeLabel: "2 days ago",
  },
  {
    id: "a9",
    type: "Communication",
    actor: "John Smith",
    action: "received an email from",
    entity: "NovaTech Systems",
    time: "2026-09-19T10:30:00",
    timeLabel: "2 days ago",
  },
  {
    id: "a10",
    type: "Tasks",
    actor: "Emma Davis",
    action: "created a follow-up task for",
    entity: "BluePeak Consulting",
    time: "2026-09-18T16:00:00",
    timeLabel: "3 days ago",
  },
  {
    id: "a11",
    type: "Leads",
    actor: "Alex Morgan",
    action: "won the deal with",
    entity: "TechVista",
    time: "2026-09-18T12:15:00",
    timeLabel: "3 days ago",
  },
  {
    id: "a12",
    type: "Clients",
    actor: "Emma Davis",
    action: "flagged as At Risk",
    entity: "GrowthLabs",
    time: "2026-09-17T09:40:00",
    timeLabel: "4 days ago",
  },
  {
    id: "a13",
    type: "Communication",
    actor: "Priya Nair",
    action: "logged a call with",
    entity: "BrightWorks Agency",
    time: "2026-09-17T08:00:00",
    timeLabel: "4 days ago",
  },
  {
    id: "a14",
    type: "Tasks",
    actor: "John Smith",
    action: "completed a task for",
    entity: "PixelWorks",
    time: "2026-09-16T17:20:00",
    timeLabel: "5 days ago",
  },
  {
    id: "a15",
    type: "Leads",
    actor: "Emma Davis",
    action: "marked as Lost",
    entity: "Charlotte King",
    time: "2026-09-15T14:50:00",
    timeLabel: "6 days ago",
  },
]

export const notifications: AppNotification[] = [
  {
    id: "not1",
    title: "Follow-up due tomorrow",
    detail: "Follow-up with Acme Digital is due tomorrow.",
    timeLabel: "5 minutes ago",
    read: false,
  },
  {
    id: "not2",
    title: "New lead assigned",
    detail: "A new lead, James Anderson, was assigned to you.",
    timeLabel: "1 hour ago",
    read: false,
  },
  {
    id: "not3",
    title: "Proposal deadline approaching",
    detail: "The proposal for Vertex Solutions is due in 2 days.",
    timeLabel: "3 hours ago",
    read: false,
  },
  {
    id: "not4",
    title: "Task completed",
    detail: "John Smith completed a task for NovaTech Systems.",
    timeLabel: "Yesterday",
    read: true,
  },
  {
    id: "not5",
    title: "Client flagged at risk",
    detail: "GrowthLabs has been flagged as At Risk.",
    timeLabel: "4 days ago",
    read: true,
  },
]

export const pipelineStages = [
  { stage: "New Lead", key: "New", count: 42, value: 84000 },
  { stage: "Contacted", key: "Contacted", count: 31, value: 96000 },
  { stage: "Qualified", key: "Qualified", count: 24, value: 112000 },
  { stage: "Proposal", key: "Proposal", count: 18, value: 128500 },
  { stage: "Negotiation", key: "Negotiation", count: 11, value: 98000 },
  { stage: "Won", key: "Won", count: 8, value: 76000 },
] as const

export const opportunityTrend = [
  { month: "Jan", value: 42000 },
  { month: "Feb", value: 58000 },
  { month: "Mar", value: 74000 },
  { month: "Apr", value: 69000 },
  { month: "May", value: 92000 },
  { month: "Jun", value: 108000 },
  { month: "Jul", value: 96000 },
  { month: "Aug", value: 118000 },
  { month: "Sep", value: 128500 },
]

export const kpis = {
  totalLeads: 248,
  totalLeadsTrend: 12.5,
  activeClients: 42,
  activeClientsTrend: 8.2,
  openOpportunities: 128500,
  openOpportunitiesTrend: 14.6,
  pendingTasks: 18,
  dueToday: 5,
}
